# Generated by Django 4.1 on 2022-08-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Picture', models.ImageField(upload_to='')),
                ('Decription', models.CharField(max_length=300)),
                ('Place', models.CharField(max_length=300)),
                ('ManagersName', models.CharField(max_length=30)),
                ('ManagersPhone', models.CharField(max_length=20)),
                ('ManagersEmail', models.CharField(max_length=30)),
                ('Direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateNTime', models.DateTimeField(max_length=100)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.team')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.direction')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.team')),
                ('TgUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tguser')),
            ],
        ),
    ]
