# Generated by Django 4.1 on 2022-09-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=30)),
                ('EditMessId', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Picture', models.ImageField(upload_to='static/photos/')),
                ('Decription', models.CharField(max_length=2000)),
                ('Place', models.CharField(max_length=300)),
                ('Vk', models.CharField(max_length=300)),
                ('Contacts', models.CharField(max_length=1000)),
                ('Prompt', models.CharField(max_length=2000)),
                ('Time', models.CharField(max_length=300)),
                ('Direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.direction')),
            ],
        ),
        migrations.CreateModel(
            name='MessageForDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_id', models.BigIntegerField(null=True)),
                ('TgUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tguser')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.IntegerField()),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.team')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('IsViewd', models.BooleanField(default=False)),
                ('IsFinished', models.BooleanField(default=False)),
                ('Date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.date')),
                ('Direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.direction')),
                ('Team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.team')),
                ('TgUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tguser')),
            ],
        ),
    ]
