# Generated by Django 4.1 on 2022-09-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='Date',
            field=models.CharField(max_length=300),
        ),
    ]
