# Generated by Django 4.1 on 2022-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Picture',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
