# Generated by Django 4.1 on 2022-08-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_team_picture_alter_tguser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
