# Generated by Django 4.1 on 2022-08-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='IsFinished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='IsViewd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='Direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.direction'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.team'),
        ),
    ]
