# Generated by Django 4.1 on 2022-09-04 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='Team',
        ),
        migrations.CreateModel(
            name='DateTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.date')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.team')),
            ],
        ),
    ]
