# Generated by Django 4.1 on 2022-08-12 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_application_isfinished_application_isviewd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_id', models.BigIntegerField(null=True)),
                ('TgUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tguser')),
            ],
        ),
    ]
