# Generated by Django 4.1 on 2022-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_application_date_alter_team_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='EditMessId',
            field=models.BigIntegerField(null=True),
        ),
    ]
